# Generated by Django 5.2.4 on 2025-07-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_tag_note_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
